// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI7WyUjUG_933_PEdXeY8MI_D4c1XTeho',
    appId: '1:966535779882:web:f2269cf7ef9963b4479553',
    messagingSenderId: '966535779882',
    projectId: 'awesome-app-flutter',
    authDomain: 'awesome-app-flutter.firebaseapp.com',
    storageBucket: 'awesome-app-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_lQZWOXGn8DLMDl35vKjiKz9elVf4Rfc',
    appId: '1:966535779882:android:3380e55725a81a90479553',
    messagingSenderId: '966535779882',
    projectId: 'awesome-app-flutter',
    storageBucket: 'awesome-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1StVrGKifxOS838fCZtIGZ1-0GHzJgbI',
    appId: '1:966535779882:ios:a264aa00bc627119479553',
    messagingSenderId: '966535779882',
    projectId: 'awesome-app-flutter',
    storageBucket: 'awesome-app-flutter.appspot.com',
    androidClientId: '966535779882-mf53p8rdnecl1jgqb91lc6gbdmo5j9kj.apps.googleusercontent.com',
    iosClientId: '966535779882-u0jpg4pqnfbj09rap788v5fq8u1gkmdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.awesomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1StVrGKifxOS838fCZtIGZ1-0GHzJgbI',
    appId: '1:966535779882:ios:a9b9b68601b96c3e479553',
    messagingSenderId: '966535779882',
    projectId: 'awesome-app-flutter',
    storageBucket: 'awesome-app-flutter.appspot.com',
    androidClientId: '966535779882-mf53p8rdnecl1jgqb91lc6gbdmo5j9kj.apps.googleusercontent.com',
    iosClientId: '966535779882-685ngau8ei1lmipi3gghj5e73gem5mb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.awesomeApp.macos',
  );
}
